apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
versions:
  kubernetes: v1.23.3
cloudProvider:
  aws: {}
containerRuntime:
  containerd: {}
addons:
  enable: true
  path: "./addons"
  addons:
    - name: cluster-autoscaler
