apiVersion: kubermatic.k8s.io/v1
kind: User
metadata:
  name: z5iofwikyaz1iarfn2rgfupph0vsma2p
spec:
  admin: true
  email: michal@kubermatic.com
  id: NcMF69XzsUrIYHFjnJeplvrxk7EmiAQL
  name: michal@kubermatic.com